/*
Write a C program to find the Greatest Common Divisor (GCD) of two given numbers
*/
#include <stdio.h>

int main() {
    int num1, num2, i, gcd;
    printf("Enter two numbers: ");
    scanf("%d %d", &num1, &num2);

    for(i=1; i <= num1 && i <= num2; ++i) {
        // Checks if i is factor of both integers
        if(num1%i==0 && num2%i==0)
            gcd = i;
    }

    printf("GCD of %d and %d is %d", num1, num2, gcd);
    return 0;
}

/*
Intrepretation:

The above code generated by Github Copilot fails to use the proper naming of the variables. The user or the developer looking at the code might get confused on the naming of the variables. The variables num1 and num2 could have been something more specific and developer friendly. It does add comments where ever required but doesnot include () for the conditional statements (if) where more than two conditions are being checked.
*/